//local host
###
GET http://localhost:8080
###
GET http://localhost:8080/events
###
POST http://localhost:8080/events HTTP/1.1
Content-Type: application/json

{
    "time": "01:00PM",
    "date": "01/01/22",
    "venueID": "62896a701617555152a9dc70",
    "ageGroup": "test",
    "food": "test food",
    "sponsor": "test",
    "theme": "fancy test",
    "cause": "API test",
    "eventPlanner": "Dr test"
}
###
PUT http://localhost:8080/events/62ae9d82b7babd07e566caa9 HTTP/1.1
Content-Type: application/json

{
    "time": "10:30AM",
    "date": "09/11/22",
    "venueID": "62ae98c4737f9cae42a8a823",
    "ageGroup": "All Ages",
    "food": "Mexican",
    "sponsor": "Medical Center",
    "theme": "Disco",
    "cause": "Health for Life",
    "eventPlanner": "Chief of Medicine"
}

###
POST http://localhost:8080/events/ HTTP/1.1
Content-Type: application/json

{
    "time": "12:30AM",
    "date": "08/04/22",
    "venueID": "62ae98c4737f9cae42a8a823",
    "ageGroup": "Adults",
    "food": "BBQ",
    "sponsor": "Golf Classic",
    "theme": "Golf",
    "cause": "Finding Jobs",
    "eventPlanner": "Golf Pro"
}
###
PUT http://localhost:8080/venues/62ae98c4737f9cae42a8a823 HTTP/1.1
Content-Type: application/json

{
    "address": "888 Fun updataed Town",
    "locationName": "Happyupdataed  day",
    "capacity": 200,
    "indoor": true
}

###
POST http://localhost:8080/venues/ HTTP/1.1
Content-Type: application/json

{
    "address": "888 Fun Town",
    "locationName": "Happy day",
    "capacity": 200,
    "indoor": true
}

###
DELETE http://localhost:8080/events/629d23927038814afdd6114a